import curses,curses.panel,curses.ascii
win=curses.initscr()
curses.curs_set(0)	
curses.start_color()
curses.init_pair(1,curses.COLOR_CYAN,curses.COLOR_WHITE)
curses.init_pair(2,curses.COLOR_RED,curses.COLOR_WHITE)
size=win.getmaxyx()
win.bkgd(curses.color_pair(1))
win.keypad(1)
win.nodelay(1)
win.border('|','|','*','*','(',')','(',')')
win.getch()
win.addstr(size[0]/2-5,2," .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------.  .----------------. ",curses.color_pair(2))
win.addstr(size[0]/2-4,2,"| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |",curses.color_pair(2))
win.addstr(size[0]/2-3,2,"| |  ________    | || |  _________   | || |  _________   | || | _____  _____ | || |    _______   | || |  _________   | || |  _______     | |",curses.color_pair(2))
win.addstr(size[0]/2-2,2,"| | |_   ___ `.  | || | |_   ___  |  | || | |_   ___  |  | || ||_   _||_   _|| || |   /  ___  |  | || | |_   ___  |  | || | |_   __ \    | |",curses.color_pair(2))
win.addstr(size[0]/2-1,2,"| |   | |   `. \ | || |   | |_  \_|  | || |   | |_  \_|  | || |  | |    | |  | || |  |  (__ \_|  | || |   | |_  \_|  | || |   | |__) |   | |",curses.color_pair(2))
win.addstr(size[0]/2,2,"| |   | |    | | | || |   |  _|  _   | || |   |  _|      | || |  | '    ' |  | || |   '.___`-.   | || |   |  _|  _   | || |   |  __ /    | |",curses.color_pair(2))
win.addstr(size[0]/2+1,2,"| |  _| |___.' / | || |  _| |___/ |  | || |  _| |_       | || |   \ `--' /   | || |  |`\____) |  | || |  _| |___/ |  | || |  _| |  \ \_  | |",curses.color_pair(2))
win.addstr(size[0]/2+2,2,"| | |________.'  | || | |_________|  | || | |_____|      | || |    `.__.'    | || |  |_______.'  | || | |_________|  | || | |____| |___| | |",curses.color_pair(2))
win.addstr(size[0]/2+3,2,"| |              | || |              | || |              | || |              | || |              | || |              | || |              | |",curses.color_pair(2))
win.addstr(size[0]/2+4,2,"| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |",curses.color_pair(2))
win.addstr(size[0]/2+5,2," '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------'  '----------------' ",curses.color_pair(2))
win.refresh()
win.clear()
win.border('|','|','*','*','(',')','(',')')
curses.delay_output(800)
curses.endwin()
