import curses,curses.panel,curses.ascii
win=curses.initscr()
curses.curs_set(0)	
curses.start_color()
curses.init_pair(1,curses.COLOR_CYAN,curses.COLOR_WHITE)
curses.init_pair(2,curses.COLOR_RED,curses.COLOR_WHITE)
size=win.getmaxyx()
b="The Good Guy !!!!!"
x=[b[0:j] for j in range(1,len(b)+1)]
win.bkgd(curses.color_pair(1))
win.keypad(1)
win.nodelay(1)
win.border('|','|','*','*','(',')','(',')')
win.getch()
for i in x:
	win.addstr(size[0]-24,5,"				       _____",curses.color_pair(2))
	win.addstr(size[0]-23,5," 				      |     |",curses.color_pair(2))
	win.addstr(size[0]-22,5,"                                 | | | |",curses.color_pair(2))
	win.addstr(size[0]-21,5,"                                 |_____|",curses.color_pair(2))
	win.addstr(size[0]-20,5,"                           ____ ___|_|___ ____",curses.color_pair(2))
	win.addstr(size[0]-19,5,"                          ()___)         ()___)",curses.color_pair(2))
	win.addstr(size[0]-18,5,"                          // /|           |\ \\\ ",curses.color_pair(2))
	win.addstr(size[0]-17,5,"                         // / |           | \ \\\ ",curses.color_pair(2))
	win.addstr(size[0]-16,5,"                        (___) |___________| (___)",curses.color_pair(2))
	win.addstr(size[0]-15,5,"                        (___)   (_______)   (___)",curses.color_pair(2))
	win.addstr(size[0]-14,5,"                        (___)     (___)     (___)",curses.color_pair(2))
	win.addstr(size[0]-13,5,"                        (___)      |_|      (___)",curses.color_pair(2))
	win.addstr(size[0]-12,5,"                        (___)  ___/___\___   | |",curses.color_pair(2))
	win.addstr(size[0]-11,5,"                         | |  |           |  | |",curses.color_pair(2))
	win.addstr(size[0]-10,5,"                         | |  |___________| /___\ ",curses.color_pair(2))
	win.addstr(size[0]-9,5,"                        /___\  |||     ||| //   \\\ ",curses.color_pair(2))
	win.addstr(size[0]-8,5,"                       //   \\\ |||     ||| \\\   //",curses.color_pair(2))
	win.addstr(size[0]-7,5,"                       \\\   // |||     |||  \\\ //",curses.color_pair(2))
	win.addstr(size[0]-6,5,"                        \\\ // ()__)   (__()",curses.color_pair(2))
	win.addstr(size[0]-5,5,"                              ///       \\\\\ ",curses.color_pair(2))
	win.addstr(size[0]-4,5,"                             ///         \\\\\ ",curses.color_pair(2))
	win.addstr(size[0]-3,5,"                           _///___     ___\\\\\_",curses.color_pair(2))
	win.addstr(size[0]-2,5,"                          |_______|   |_______|",curses.color_pair(2))
	curses.beep()
	win.addstr(5, size[1]/2-len(b)/2,i,curses.A_BLINK | curses.color_pair(2)|curses.A_UNDERLINE|curses.A_BOLD)
	curses.delay_output(80)
	win.refresh()
	win.clear()
	win.border('|','|','*','*','(',')','(',')')
curses.delay_output(800)
curses.endwin()
