import curses,curses.panel,curses.ascii
win=curses.initscr()
curses.curs_set(0)	
curses.start_color()
curses.init_pair(1,curses.COLOR_CYAN,curses.COLOR_WHITE)
curses.init_pair(2,curses.COLOR_RED,curses.COLOR_WHITE)
size=win.getmaxyx()
win.bkgd(curses.color_pair(1))
win.keypad(1)
win.nodelay(1)
win.border('|','|','*','*','(',')','(',')')
win.getch()
win.addstr(size[0]/2-5,20," .----------------.  .----------------.  .----------------.  .----------------.  .----------------. ",curses.color_pair(2))
win.addstr(size[0]/2-4,20,"| .--------------. || .--------------. || .--------------. || .--------------. || .--------------. |",curses.color_pair(2))
win.addstr(size[0]/2-3,20,"| |  _______     | || |     ____     | || |   ______     | || |     ____     | || |  _________   | |",curses.color_pair(2))
win.addstr(size[0]/2-2,20,"| | |_   __ \    | || |   .'    `.   | || |  |_   _ \    | || |   .'    `.   | || | |  _   _  |  | |",curses.color_pair(2))
win.addstr(size[0]/2-1,20,"| |   | |__) |   | || |  /  .--.  \  | || |    | |_) |   | || |  /  .--.  \  | || | |_/ | | \_|  | |",curses.color_pair(2))
win.addstr(size[0]/2,20,"| |   |  __ /    | || |  | |    | |  | || |    |  __'.   | || |  | |    | |  | || |     | |      | |",curses.color_pair(2))
win.addstr(size[0]/2+1,20,"| |  _| |  \ \_  | || |  \  `--'  /  | || |   _| |__) |  | || |  \  `--'  /  | || |    _| |_     | |",curses.color_pair(2))
win.addstr(size[0]/2+2,20,"| | |____| |___| | || |   `.____.'   | || |  |_______/   | || |   `.____.'   | || |   |_____|    | |",curses.color_pair(2))
win.addstr(size[0]/2+3,20,"| |              | || |              | || |              | || |              | || |              | |",curses.color_pair(2))
win.addstr(size[0]/2+4,20,"| '--------------' || '--------------' || '--------------' || '--------------' || '--------------' |",curses.color_pair(2))
win.addstr(size[0]/2+5,20," '----------------'  '----------------'  '----------------'  '----------------'  '----------------' ",curses.color_pair(2))
win.refresh()
win.clear()
win.border('|','|','*','*','(',')','(',')')
curses.delay_output(800)
curses.endwin()
