import curses,curses.panel,curses.ascii
win=curses.initscr()
curses.curs_set(0)	
curses.start_color()
curses.init_pair(1,curses.COLOR_CYAN,curses.COLOR_WHITE)
curses.init_pair(2,curses.COLOR_RED,curses.COLOR_WHITE)
size=win.getmaxyx()
b="You did Good But there are more..!!!!"
x=[b[0:j] for j in range(1,len(b)+1)]
win.bkgd(curses.color_pair(1))
win.keypad(1)
win.nodelay(1)
win.border('|','|','*','*','(',')','(',')')
win.getch()
for i in x:
	win.addstr(size[0]/2-9,size[1]/2-20,"                __________",curses.color_pair(2))
	win.addstr(size[0]/2-8,size[1]/2-20,"         ______/ ________ \______",curses.color_pair(2))
	win.addstr(size[0]/2-7,size[1]/2-20,"       _/      ____________      \_",curses.color_pair(2))
	win.addstr(size[0]/2-6,size[1]/2-20,"     _/____________    ____________\_",curses.color_pair(2))
	win.addstr(size[0]/2-5,size[1]/2-20,"    /  ___________ \  / ___________  \ ",curses.color_pair(2))
	win.addstr(size[0]/2-4,size[1]/2-20,"   /  /XXXXXXXXXXX\ \/ /XXXXXXXXXXX\  \ ",curses.color_pair(2))
	win.addstr(size[0]/2-3,size[1]/2-20,"  /  /############/    \############\  \ ",curses.color_pair(2))
	win.addstr(size[0]/2-2,size[1]/2-20,"  |  \XXXXXXXXXXX/ _  _ \XXXXXXXXXXX/  |",curses.color_pair(2))
	win.addstr(size[0]/2-1,size[1]/2-20,"__|\_____   ___   //  \\\   ___   _____/|__",curses.color_pair(2))
	win.addstr(size[0]/2,size[1]/2-20,"[_       \     \  X    X  /     /       _]",curses.color_pair(2))
	win.addstr(size[0]/2+1,size[1]/2-20,"__|     \ \                    / /     |__",curses.color_pair(2))
	win.addstr(size[0]/2+2,size[1]/2-20,"[____  \ \ \   ____________   / / /  ____]",curses.color_pair(2))
	win.addstr(size[0]/2+3,size[1]/2-20,"     \  \ \ \/||.||.||.||.||\/ / /  /",curses.color_pair(2))
	win.addstr(size[0]/2+4,size[1]/2-20,"      \_ \ \  ||.||.||.||.||  / / _/",curses.color_pair(2))
	win.addstr(size[0]/2+5,size[1]/2-20,"        \ \   ||.||.||.||.||   / /",curses.color_pair(2))
	win.addstr(size[0]/2+6,size[1]/2-20,"         \_   ||_||_||_||_||   _/",curses.color_pair(2))
	win.addstr(size[0]/2+7,size[1]/2-20,"           \    ...........   /",curses.color_pair(2))
	win.addstr(size[0]/2+8,size[1]/2-20,"            \________________/",curses.color_pair(2))
	curses.beep()
	win.addstr(5, size[1]/2-len(b)/2,i,curses.A_BLINK | curses.color_pair(2)|curses.A_UNDERLINE|curses.A_BOLD)
	curses.delay_output(80)
	win.refresh()
	win.clear()
	win.border('|','|','*','*','(',')','(',')')
curses.delay_output(1200)
curses.endwin()
